name: EpicQuest
main: main.java.randy.epicquest.EpicMain
version: 3.5.3
depend: [Vault]
softdepend: [Heroes, Citizens, BarAPI]
commands:
  q:
    description: Quest commands
    usage: /<command>
    aliases: quest