name: EpicQuest
main: randy.epicquest.EpicMain
version: 3.5.2
depend: [Vault]
softdepend: [Heroes, Citizens, BarAPI]
commands:
  q:
    description: Quest stuff
    usage: /<command> help
    aliases: quest
