name: EpicQuest
main: randy.epicquest.EpicMain
version: 3.5
depend: [Vault]
softdepend: [Heroes, Citizens, BarAPI]
commands:
  quest:
    description: Quest stuff
    usage: /<command> help
  q:
    description: Quest stuff
    usage: 