name: EpicQuest
main: main.java.randy.epicquest.EpicMain
version: 3.5.2
depend: [Vault]
softdepend: [Heroes, Citizens, BarAPI]
commands:
  q:
    description: Quest stuff
    usage: /<command>
    aliases: quest
  q help:
    description: Quest help
    usage: /<command> help
    aliases: quest help